services:
  server:
    image: ghcr.io/loicviennois/project-euler-server
    build:
      context: .
      dockerfile: ./apps/euler-server/Dockerfile
    ports:
      - '3000:3000'
  client:
    image: ghcr.io/loicviennois/project-euler-client
    build:
      context: .
      dockerfile: ./apps/euler-client/Dockerfile
    ports:
      - '8080:80'
