version: '2.4'

services:
  server:
    build:
      target: dev
    volumes:
      - ./server/src:/usr/src/app/src
  client:
    build:
      target: dev
    volumes:
      - ./client/src:/usr/src/app/src
