version: '2.4'

services:
  server:
    image: ghcr.io/loicviennois/project-euler-server
    build: ./apps/euler-server
    ports:
      - '3000:3000'
  client:
    image: ghcr.io/loicviennois/project-euler-client
    build: ./apps/euler-client
    ports:
      - '8080:80'
