version: '2.4'

services:
  server:
    image: loicviennois/project-euler-server
    build: ./server
    ports:
      - '3000:3000'
  client:
    image: loicviennois/project-euler-client
    build: ./client
    depends_on:
      - server
    ports:
      - '8080:80'
