version: '2'

services:
  server:
    image: loicviennois/project-euler-server
    build: server
    ports:
      - '3000:3000'
  client:
    image: loicviennois/project-euler-client
    build: client
    ports:
      - '8080:80'
