version: '2.4'

services:
  server:
    image: loicviennois/project-euler-server
    build: ./server
    ports:
      - '3000:3000'
    healthcheck:
      interval: 5s
  client:
    image: loicviennois/project-euler-client
    build: ./client
    depends_on:
      server:
        condition: service_healthy
    ports:
      - '8080:80'
    healthcheck:
      interval: 5s
